"""Real mountains to measure elevation against: the highest one a person has
climbed past, and the next one up.

Heights are from each mountain's English Wikipedia article or the list it is
on (states', countries' and the Solar System's highest). On Earth a height is
the summit above sea level; elsewhere it is base to peak, as the Solar System
list gives it, so the two are not the same measure. Landmarks are the peaks
worth a word when someone climbs past one: everything off Earth, Virginia's,
and the famous ones. The rest are too close together for that: below 10,000 ft
there is a new one every card or two.
"""

from bisect import bisect_right
from typing import NamedTuple, Optional
from urllib.parse import quote


class Peak(NamedTuple):
    feet: int
    name: str
    body: str
    title: str  # the Wikipedia article
    note: Optional[str]
    landmark: bool

    @property
    def url(self) -> str:
        return "https://en.wikipedia.org/wiki/" + quote(self.title)

    @property
    def where(self) -> str:
        """Its world, when that is not Earth."""
        return "" if self.body == "Earth" else "the Moon" if self.body == "Moon" else self.body


def passed(feet: int) -> Optional[Peak]:
    """The highest peak at or below this many feet."""
    i = bisect_right(_HEIGHTS, feet)
    return PEAKS[i - 1] if i else None


def ahead(feet: int) -> Optional[Peak]:
    """The next peak up, if there is one."""
    i = bisect_right(_HEIGHTS, feet)
    return PEAKS[i] if i < len(PEAKS) else None


def crossed(before: int, after: int) -> Optional[Peak]:
    """The highest landmark climbed past going from one height to the other."""
    return next((p for p in reversed(PEAKS[bisect_right(_HEIGHTS, before):bisect_right(_HEIGHTS, after)]) if p.landmark), None)


# (feet, name, body, Wikipedia title, note, landmark), lowest first.
PEAKS = [Peak(*row) for row in [
    (95, 'Rocher Clipperton', 'Earth', 'Clipperton_Island', "Clipperton Island's highest point", False),
    (115, 'Monte Testaccio', 'Earth', 'Monte_Testaccio', 'Roman hill made of broken pottery', True),
    (129, 'Silbury Hill', 'Earth', 'Silbury_Hill', 'built around 2400 BC', False),
    (138, 'Mount Wycheproof', 'Earth', 'Mount_Wycheproof', 'above the plain', False),
    (141, 'The Bluff', 'Earth', 'The_Bluff_(Cayman_Islands)', "Cayman Islands' highest point", False),
    (207, 'Mount Alvernia', 'Earth', 'Mount_Alvernia', "the Bahamas' highest point", False),
    (213, 'Command Ridge', 'Earth', 'Command_Ridge', "Nauru's highest point", False),
    (240, 'Crocus Hill', 'Earth', 'Crocus_Hill', "Anguilla's highest point", False),
    (259, 'Town Hill', 'Earth', 'Town_Hill,_Bermuda', "Bermuda's highest point", False),
    (338, 'Qurayn Abu al Bawl', 'Earth', 'Qurayn_Abu_al_Bawl', "Qatar's highest point", False),
    (345, 'Britton Hill', 'Earth', 'Britton_Hill', 'lowest US state high point', False),
    (374, 'Le Moulin', 'Earth', 'Le_Moulin', "Guernsey's highest point", False),
    (414, 'Point Reno', 'Earth', 'Fort_Reno_Park', "Washington, D.C.'s highest point", False),
    (440, 'Mountain of Smoke', 'Earth', 'Mountain_of_Smoke', "Bahrain's highest point", False),
    (446, 'Les Platons', 'Earth', 'Les_Platons', "Jersey's highest point", False),
    (448, 'Ebright Azimuth', 'Earth', 'Ebright_Azimuth', "Delaware's highest point", False),
    (518, 'Glastonbury Tor', 'Earth', 'Glastonbury_Tor', None, False),
    (531, 'Mont Agel', 'Earth', 'Mont_Agel', "Monaco's highest point", False),
    (535, 'Driskill Mountain', 'Earth', 'Driskill_Mountain', "Louisiana's highest point", False),
    (538, 'Bukit Timah Hill', 'Earth', 'Bukit_Timah_Hill', "Singapore's highest point", False),
    (561, 'Møllehøj', 'Earth', 'Møllehøj', "Denmark's highest point", False),
    (564, 'Coloane Alto', 'Earth', 'Coloane_Alto', "Macau's highest point", False),
    (617, 'Mount Jamanota', 'Earth', 'Mount_Jamanota', "Aruba's highest point", False),
    (794, 'Mount Ngerchelchuus', 'Earth', 'Mount_Ngerchelchuus', "Palau's highest point", False),
    (807, 'Woodall Mountain', 'Earth', 'Woodall_Mountain', "Mississippi's highest point", False),
    (811, 'Jerimoth Hill', 'Earth', 'Jerimoth_Hill', "Rhode Island's highest point", False),
    (823, "Arthur's Seat", 'Earth', "Arthur's_Seat", 'Edinburgh', False),
    (830, "Ta' Dmejrek", 'Earth', "Ta'_Dmejrek", "Malta's highest point", False),
    (964, 'Aukštojas Hill', 'Earth', 'Aukštojas_Hill', "Lithuania's highest point", False),
    (1024, 'Gaiziņkalns', 'Earth', 'Gaiziņkalns', "Latvia's highest point", False),
    (1043, 'Suur Munamägi', 'Earth', 'Suur_Munamägi', "Estonia's highest point", False),
    (1058, 'Vaalserberg', 'Earth', 'Vaalserberg', "the Netherlands' highest point in Europe", False),
    (1115, 'Mount Hillaby', 'Earth', 'Mount_Hillaby', "Barbados' highest point", False),
    (1132, 'Dzyarzhynskaya Hara', 'Earth', 'Dzyarzhynskaya_Hara', "Belarus' highest point", False),
    (1184, 'Murray Hill', 'Earth', 'Murray_Hill,_Christmas_Island', "Christmas Island's highest point", False),
    (1220, 'Christoffelberg', 'Earth', 'Christoffelberg', "Curaçao's highest point", False),
    (1235, 'Charles Mound', 'Earth', 'Charles_Mound', "Illinois' highest point", False),
    (1257, 'Hoosier Hill', 'Earth', 'Hoosier_Hill', "Indiana's highest point", False),
    (1299, 'Sugarloaf Mountain', 'Earth', 'Sugarloaf_Mountain', 'Rio de Janeiro', True),
    (1319, 'Boggy Peak', 'Earth', 'Boggy_Peak', "Antigua's highest point", False),
    (1332, 'Mount Lamlam', 'Earth', 'Mount_Lamlam', 'Guam; over 37,000 ft from the Mariana Trench', False),
    (1391, 'Pic Paradis', 'Earth', 'Pic_Paradis', "Saint Martin's highest point", False),
    (1398, 'Rock of Gibraltar', 'Earth', 'Rock_of_Gibraltar', None, False),
    (1411, 'Bălănești Hill', 'Earth', 'Bălănești_Hill', "Moldova's highest point", False),
    (1548, 'Campbell Hill', 'Earth', 'Campbell_Hill_(Ohio)', "Ohio's highest point", False),
    (1556, 'Crown Mountain', 'Earth', 'Crown_Mountain_(United_States_Virgin_Islands)', "US Virgin Islands' highest point", False),
    (1671, 'Hawkeye Point', 'Earth', 'Hawkeye_Point', "Iowa's highest point", False),
    (1685, 'Cerro Catedral', 'Earth', 'Cerro_Catedral_(Uruguay)', "Uruguay's highest point", False),
    (1703, 'Mill Mountain', 'Earth', 'Roanoke_Star', 'home of the Roanoke Star', True),
    (1772, 'Taum Sauk Mountain', 'Earth', 'Taum_Sauk_Mountain', "Missouri's highest point", False),
    (1802, 'High Point', 'Earth', 'High_Point_(New_Jersey)', "New Jersey's highest point", False),
    (1837, 'Kneiff', 'Earth', 'Kneiff', "Luxembourg's highest point", False),
    (1926, 'Paris Mountain', 'Earth', 'Paris_Mountain', 'northern Virginia', True),
    (1951, 'Timms Hill', 'Earth', 'Timms_Hill', "Wisconsin's highest point", False),
    (1979, 'Mount Arvon', 'Earth', 'Mount_Arvon', "Michigan's highest point", False),
    (1990, 'Tri-State Peak', 'Earth', 'Tri-State_Peak', 'Kentucky, Tennessee and Virginia meet here', True),
    (2034, 'Spesard Knob', 'Earth', 'Spesard_Knob', 'Craig County', True),
    (2037, 'Snaefell', 'Earth', 'Snaefell', "Isle of Man's highest point", False),
    (2106, 'Signal Knob', 'Earth', 'Signal_Knob', 'a Civil War signal station', True),
    (2139, 'Te Manga', 'Earth', 'Te_Manga', "Cook Islands' highest point", False),
    (2159, 'Mont Sokbaro', 'Earth', 'Mont_Sokbaro', "Benin's highest point", False),
    (2277, 'Signal de Botrange', 'Earth', 'Signal_de_Botrange', "Belgium's highest point", False),
    (2302, 'Eagle Mountain', 'Earth', 'Eagle_Mountain_(Minnesota)', "Minnesota's highest point", False),
    (2313, 'Mount Usborne', 'Earth', 'Mount_Usborne', "Falklands' highest point", False),
    (2386, 'Mount Frissell', 'Earth', 'Mount_Frissell', "Connecticut's highest point (on its slope)", False),
    (2405, 'Cheaha Mountain', 'Earth', 'Cheaha_Mountain', "Alabama's highest point", False),
    (2425, 'Monte Titano', 'Earth', 'Monte_Titano', 'San Marino sits on it', False),
    (2451, 'Mount Tenakourou', 'Earth', 'Mount_Tenakourou', "Burkina Faso's highest point", False),
    (2513, 'Tazing Dong', 'Earth', 'Tazing_Dong', "Bangladesh's highest point", False),
    (2559, 'Olavtoppen', 'Earth', 'Olavtoppen', 'Bouvet Island, the remotest island', False),
    (2566, 'Nanlaud', 'Earth', 'Nanlaud', "Micronesia's highest point", False),
    (2671, "Twelve O'clock Knob", 'Earth', "Twelve_O'clock_Knob", 'the sun stands over it near noon', True),
    (2684, "Diana's Peak", 'Earth', "Diana's_Peak", "Saint Helena's highest point", False),
    (2753, 'Mount Magazine', 'Earth', 'Mount_Magazine', "Arkansas' highest point", False),
    (2756, 'Mount Saint Catherine', 'Earth', 'Mount_Saint_Catherine,_Grenada', "Grenada's highest point", False),
    (2762, 'Cerro Peró', 'Earth', 'Cerro_Peró', "Paraguay's highest point", False),
    (2792, "Bellevue de l'Inini", 'Earth', "Bellevue_de_l'Inini", "French Guiana's highest point", False),
    (2831, 'Uluru', 'Earth', 'Uluru', '1,142 ft above the plain', True),
    (2854, 'Mount Scenery', 'Earth', 'Mount_Scenery', 'highest point of the Kingdom of the Netherlands', False),
    (2887, 'Slættaratindur', 'Earth', 'Slættaratindur', "Faroe Islands' highest point", False),
    (2964, 'Big Schloss', 'Earth', 'Big_Schloss', "'Schloss' is German for castle", True),
    (2969, 'Morne Seychellois', 'Earth', 'Morne_Seychellois', "Seychelles' highest point", False),
    (3002, 'Kediet ej Jill', 'Earth', 'Kediet_ej_Jill', "Mauritania's highest point", False),
    (3080, 'El Cerro del Aripo', 'Earth', 'El_Cerro_del_Aripo', "Trinidad's highest point", False),
    (3120, 'Mount Gimie', 'Earth', 'Mount_Gimie', "Saint Lucia's highest point", False),
    (3140, 'Tai Mo Shan', 'Earth', 'Tai_Mo_Shan', "Hong Kong's highest point", False),
    (3169, 'Lata Mountain', 'Earth', 'Lata_Mountain', "American Samoa's highest point", False),
    (3197, 'McAfee Knob', 'Earth', 'McAfee_Knob', 'the most photographed spot on the Appalachian Trail', True),
    (3204, 'Mount Agrihan', 'Earth', 'Mount_Agrihan', "Northern Mariana Islands' highest point", False),
    (3213, 'Mount Davis', 'Earth', 'Mount_Davis_(Pennsylvania)', "Pennsylvania's highest point", False),
    (3235, 'Mount Agou', 'Earth', 'Mount_Agou', "Togo's highest point", False),
    (3250, 'Brushy Mountain', 'Earth', 'Brushy_Mountain_(conservation_area)', 'on the AT, Bland County', True),
    (3260, 'Fort Lewis Mountain', 'Earth', 'Fort_Lewis_Mountain', 'between Blacksburg and Salem', True),
    (3284, 'Old Rag Mountain', 'Earth', 'Old_Rag_Mountain', 'Shenandoah', True),
    (3327, 'Kékes', 'Earth', 'Kékes', "Hungary's highest point", False),
    (3346, 'Mont Nabemba', 'Earth', 'Mont_Nabemba', "Republic of the Congo's highest point", False),
    (3370, 'Hoye-Crest', 'Earth', 'Hoye-Crest', "Maryland's highest point", False),
    (3379, 'Mount Nabi Yunis', 'Earth', 'Mount_Nabi_Yunis,_Palestine', "Palestine's highest point", False),
    (3380, 'Kao', 'Earth', 'Kao_(island)', "Tonga's highest point, a volcanic island", False),
    (3409, 'Carrauntoohil', 'Earth', 'Carrauntoohil', "Ireland's highest point", False),
    (3489, 'Mount Greylock', 'Earth', 'Mount_Greylock', "Massachusetts' highest point", False),
    (3506, 'White Butte', 'Earth', 'White_Butte_(North_Dakota)', "North Dakota's highest point", False),
    (3510, 'Mont Bengoué', 'Earth', 'Mont_Bengoué', "Gabon's highest point", False),
    (3554, 'Sassafras Mountain', 'Earth', 'Sassafras_Mountain', "South Carolina's highest point", False),
    (3558, 'Table Mountain', 'Earth', 'Table_Mountain', 'the only land feature to name a constellation', True),
    (3638, 'Sinking Creek Mountain', 'Earth', 'Sinking_Creek_Mountain', 'Chimney Rock, Craig County', True),
    (3645, 'House Mountain', 'Earth', 'House_Mountain_(Rockbridge_County,_Virginia)', 'near Lexington', True),
    (3688, "Doyle's Delight", 'Earth', "Doyle's_Delight", "Belize's highest point", False),
    (3789, 'Hombori Tondo', 'Earth', 'Hombori_Tondo', "Mali's highest point", False),
    (3793, 'Mount Liamuiga', 'Earth', 'Mount_Liamuiga', "St Kitts' highest point", False),
    (3875, 'Sharp Top', 'Earth', 'Peaks_of_Otter', 'Peaks of Otter, Blue Ridge Parkway', True),
    (3950, 'Mount Hermon', 'Earth', 'Mount_Hermon', "Israel's highest point (2,814 m in Syria)", False),
    (3960, 'Buffalo Mountain', 'Earth', 'Buffalo_Mountain_Natural_Area_Preserve', 'Floyd County, Virginia', True),
    (4011, 'Stony Man Mountain', 'Earth', 'Stony_Man_Mountain', 'Shenandoah National Park', True),
    (4041, 'Mount Sunflower', 'Earth', 'Mount_Sunflower', "Kansas' highest point", False),
    (4052, 'La Soufrière', 'Earth', 'La_Soufrière_(Saint_Vincent)', "St Vincent's volcano", False),
    (4063, 'The Priest', 'Earth', 'The_Priest_(mountain)', 'Nelson County', True),
    (4139, 'Black Mountain', 'Earth', 'Black_Mountain_(Kentucky)', "Kentucky's highest point", False),
    (4200, 'Julianatop', 'Earth', 'Julianatop', "Suriname's highest point", False),
    (4203, 'Mount Vesuvius', 'Earth', 'Mount_Vesuvius', 'buried Pompeii in AD 79', True),
    (4223, 'High Knob', 'Earth', 'High_Knob', '200 inches of snow one winter', True),
    (4224, 'Apple Orchard Mountain', 'Earth', 'Apple_Orchard_Mountain', "Virginia's most prominent peak", True),
    (4300, 'Mons Rümker', 'Moon', 'Mons_Rümker', 'a volcanic dome field', True),
    (4344, 'Tomanivi', 'Earth', 'Tomanivi', "Fiji's highest point", False),
    (4361, 'Salt Pond Mountain', 'Earth', 'Salt_Pond_Mountain', 'Mountain Lake, Giles County', True),
    (4390, 'Cerro de Punta', 'Earth', 'Cerro_de_Punta', "Puerto Rico's highest point", False),
    (4395, 'Mount Mansfield', 'Earth', 'Mount_Mansfield', "Vermont's highest point", False),
    (4397, 'Reddish Knob', 'Earth', 'Reddish_Knob', 'a road runs to the top', True),
    (4413, 'Ben Nevis', 'Earth', 'Ben_Nevis', "the UK's highest point", True),
    (4463, 'Elliott Knob', 'Earth', 'Elliott_Knob', 'Great North Mountain', True),
    (4583, 'Mount Pelée', 'Earth', 'Mount_Pelée', 'Martinique; its 1902 eruption killed ~28,000', False),
    (4626, 'Mont Ngaoui', 'Earth', 'Mont_Ngaoui', "Central African Republic's highest point", False),
    (4747, 'Morne Diablotins', 'Earth', 'Morne_Diablotins', "Dominica's highest point", False),
    (4757, 'Doom Mons', 'Titan', 'Doom_Mons', 'named after Mount Doom', True),
    (4784, 'Brasstown Bald', 'Earth', 'Brasstown_Bald', "Georgia's highest point", False),
    (4813, 'La Grande Soufrière', 'Earth', 'La_Grande_Soufrière', "Guadeloupe's highest point", False),
    (4862, 'Spruce Knob', 'Earth', 'Spruce_Knob', "West Virginia's highest point", False),
    (4902, 'Otse Hill', 'Earth', 'Otse_Hill', "Botswana's highest point", False),
    (4975, 'Black Mesa', 'Earth', 'Black_Mesa_(Oklahoma)', "Oklahoma's highest point", False),
    (5066, 'Jebel ech Chambi', 'Earth', 'Jebel_ech_Chambi', "Tunisia's highest point", False),
    (5259, 'Sněžka', 'Earth', 'Sněžka', "Czech Republic's highest point", False),
    (5270, 'Mount Katahdin', 'Earth', 'Mount_Katahdin', 'northern end of the Appalachian Trail', False),
    (5341, 'Mont Panié', 'Earth', 'Mont_Panié', "New Caledonia's highest point", False),
    (5343, 'Mount Marcy', 'Earth', 'Mount_Marcy', "New York's highest point", False),
    (5432, 'Panorama Point', 'Earth', 'Panorama_Point', "Nebraska's highest point", False),
    (5525, 'Whitetop Mountain', 'Earth', 'Whitetop_Mountain', "Virginia's second highest", True),
    (5620, 'Newtontoppen', 'Earth', 'Newtontoppen', "Svalbard's highest point", False),
    (5729, 'Mount Rogers', 'Earth', 'Mount_Rogers', "Virginia's highest point; wild ponies roam it", True),
    (5748, 'Mont Nimba', 'Earth', 'Mont_Nimba', "Guinea and Ivory Coast's highest point", False),
    (5948, 'Phnom Aural', 'Earth', 'Phnom_Aural', "Cambodia's highest point", False),
    (6007, 'Dinara', 'Earth', 'Dinara', "Croatia's highest point", False),
    (6070, 'Mont Ross', 'Earth', 'Mont_Ross', 'Kerguelen Islands', False),
    (6083, 'Jabal Umm ad Dami', 'Earth', 'Jabal_Umm_ad_Dami', "Jordan's highest point", False),
    (6096, 'Silisili', 'Earth', 'Silisili', "Samoa's highest point", False),
    (6109, 'Emlembe', 'Earth', 'Emlembe', "Eswatini's highest point", False),
    (6152, 'Bukit Pagon', 'Earth', 'Bukit_Pagon', "Brunei's highest point", False),
    (6283, 'Jirisan', 'Earth', 'Jirisan', "mainland South Korea's highest point", False),
    (6288, 'Mount Washington', 'Earth', 'Mount_Washington_(New_Hampshire)', '231 mph wind record, 1934', True),
    (6345, 'Jebel Jais', 'Earth', 'Jebel_Jais', "summit in Oman; world's longest zipline", False),
    (6381, 'Mount Bintumani', 'Earth', 'Mount_Bintumani', "Sierra Leone's highest point", False),
    (6404, 'Mount Olympus (Cyprus)', 'Earth', 'Mount_Olympus_(Cyprus)', "Cyprus' highest point", False),
    (6476, 'Pico Turquino', 'Earth', 'Pico_Turquino', "Cuba's highest point", False),
    (6568, 'Mont Idoukal-n-Taghès', 'Earth', 'Mont_Idoukal-n-Taghès', "Niger's highest point", False),
    (6631, 'Mousa Ali', 'Earth', 'Mousa_Ali', "Djibouti's highest point", False),
    (6640, 'Pico de São Tomé', 'Earth', 'Pico_de_São_Tomé', "São Tomé's highest point", False),
    (6643, 'Kuwohi', 'Earth', 'Kuwohi', "Tennessee's highest point (formerly Clingmans Dome)", False),
    (6684, 'Mount Mitchell', 'Earth', 'Mount_Mitchell', 'highest point east of the Mississippi', True),
    (6762, 'Hoverla', 'Earth', 'Hoverla', "Ukraine's highest point", False),
    (6841, 'Mogotón', 'Earth', 'Mogotón', "Nicaragua's highest point", False),
    (6879, 'Kebnekaise', 'Earth', 'Kebnekaise', "Sweden's highest point", False),
    (6921, 'Hvannadalshnúkur', 'Earth', 'Hvannadalshnúkur', "Iceland's highest point", False),
    (7116, 'Midžor', 'Earth', 'Midžor', "Serbia's highest point", False),
    (7244, 'Black Elk Peak', 'Earth', 'Black_Elk_Peak', "South Dakota's highest point", False),
    (7310, 'Mount Kosciuszko', 'Earth', 'Mount_Kosciuszko', "Australia's highest point", True),
    (7352, 'Mont Orohena', 'Earth', 'Mont_Orohena', "Tahiti's highest point", False),
    (7402, 'Blue Mountain Peak', 'Earth', 'Blue_Mountain_Peak', 'Jamaica; coffee grows on its slopes', False),
    (7438, 'Bikku Bitti', 'Earth', 'Bikku_Bitti', "Libya's highest point", False),
    (7661, 'Mount Popomanaseu', 'Earth', 'Mount_Popomanaseu', "Solomon Islands' highest point", False),
    (7674, 'Mafinga Hills', 'Earth', 'Mafinga_Hills', "Zambia's highest point", False),
    (7713, 'Mount Pico', 'Earth', 'Mount_Pico', "Portugal's highest point, in the Azores", False),
    (7746, 'Karthala', 'Earth', 'Mount_Karthala', "Comoros' highest point, an active volcano", False),
    (7828, 'Maglić', 'Earth', 'Maglić_(mountain)', "Bosnia and Herzegovina's highest point", False),
    (7936, 'Chappal Waddi', 'Earth', 'Chappal_Waddi', "Nigeria's highest point", False),
    (8005, 'Monte Binga', 'Earth', 'Monte_Binga', "Mozambique's highest point", False),
    (8070, 'Mount Shimbiris', 'Earth', 'Mount_Shimbiris', "Somalia's highest point", False),
    (8100, 'Galdhøpiggen', 'Earth', 'Galdhøpiggen', "Norway's highest point", False),
    (8281, 'Pidurutalagala', 'Earth', 'Pidurutalagala', "Sri Lanka's highest point", False),
    (8363, 'Mount St. Helens', 'Earth', 'Mount_St._Helens', 'lost 1,300 ft in 1980', False),
    (8415, 'Doi Inthanon', 'Earth', 'Doi_Inthanon', "Thailand's highest point", False),
    (8442, 'Königstein', 'Earth', 'Königstein,_Namibia', "Namibia's highest point", False),
    (8504, 'Mount Nyangani', 'Earth', 'Mount_Nyangani', "Zimbabwe's highest point", False),
    (8527, 'Grauspitz', 'Earth', 'Grauspitz', "Liechtenstein's highest point", False),
    (8596, 'Mount Moco', 'Earth', 'Mount_Moco', "Angola's highest point", False),
    (8625, 'Mount Catherine', 'Earth', 'Mount_Catherine', "Egypt's highest point, beside Mount Sinai", False),
    (8709, 'Gerlachovský štít', 'Earth', 'Gerlachovský_štít', "Slovakia's highest point", False),
    (8728, 'Velika Rudoka', 'Earth', 'Velika_Rudoka', "Kosovo's highest point", False),
    (8751, 'Guadalupe Peak', 'Earth', 'Guadalupe_Peak', "Texas' highest point", False),
    (8793, 'Pic la Selle', 'Earth', 'Pic_la_Selle', "Haiti's highest point", False),
    (8806, 'Mount Heha', 'Earth', 'Mount_Heha', "Burundi's highest point", False),
    (8957, 'Cerro El Pital', 'Earth', 'Cerro_El_Pital', "El Salvador's highest point", False),
    (9003, 'Paektu-san', 'Earth', 'Paektu_Mountain', "North Korea's highest point, a volcano", False),
    (9006, 'Big Ben', 'Earth', 'Big_Ben_(Heard_Island)', 'an active volcano on Heard Island', False),
    (9068, 'Korab', 'Earth', 'Korab_(mountain)', "Albania and North Macedonia's highest point", False),
    (9094, 'Mount Roraima', 'Earth', 'Mount_Roraima', 'the tepui behind The Lost World', False),
    (9281, 'Pico do Fogo', 'Earth', 'Pico_do_Fogo', "Cape Verde's highest point", False),
    (9285, 'Phou Bia', 'Earth', 'Phou_Bia', "Laos' highest point", False),
    (9396, 'Triglav', 'Earth', 'Triglav', "Slovenia's highest point; it's on the flag", False),
    (9416, 'Cerro Las Minas', 'Earth', 'Cerro_Las_Minas', "Honduras' highest point", False),
    (9436, 'Maromokotro', 'Earth', 'Maromokotro', "Madagascar's highest point", False),
    (9541, 'Mount Tahat', 'Earth', 'Mount_Tahat', "Algeria's highest point", False),
    (9573, 'Mount Olympus', 'Earth', 'Mount_Olympus', 'home of the Greek gods', True),
    (9596, 'Musala', 'Earth', 'Musala', "Bulgaria's highest point", False),
    (9656, 'Coma Pedrosa', 'Earth', 'Coma_Pedrosa', "Andorra's highest point", False),
    (9692, 'Mount Apo', 'Earth', 'Mount_Apo', "the Philippines' highest point", False),
    (9718, 'Zugspitze', 'Earth', 'Zugspitze', "Germany's highest point", False),
    (9721, 'Tatamailau', 'Earth', 'Tatamailau', "Timor-Leste's highest point", False),
    (9826, 'Pico da Neblina', 'Earth', 'Pico_da_Neblina', "Brazil's highest point, 'peak of the mist'", False),
    (9843, 'Caloris Montes', 'Mercury', 'Caloris_Montes', "rim of Mercury's biggest crater", True),
    (9849, 'Mount Mulanje', 'Earth', 'Mount_Mulanje', "Malawi's highest point", False),
    (9879, 'Pico Basilé', 'Earth', 'Pico_Basilé', "Equatorial Guinea's highest point", False),
    (9892, 'Jabal as-Sūda', 'Earth', 'Jabal_as-Sūda', "Saudi Arabia's highest point", False),
    (9902, 'Emba Soira', 'Earth', 'Emba_Soira', "Eritrea's highest point", False),
    (9902, 'Jabal Shams', 'Earth', 'Jabal_Shams', "Oman's highest point", False),
    (10072, 'Piton des Neiges', 'Earth', 'Piton_des_Neiges', "Réunion's highest point", False),
    (10131, "Qurnat as Sawda'", 'Earth', "Qurnat_as_Sawda'", "Lebanon's highest point", False),
    (10174, 'Pico Duarte', 'Earth', 'Pico_Duarte', 'highest point in the Caribbean', False),
    (10326, 'Fansipan', 'Earth', 'Fansipan', "Vietnam's highest point", False),
    (10456, 'Kinyeti', 'Earth', 'Kinyeti', "South Sudan's highest point", False),
    (10948, 'Mithrim Montes', 'Titan', 'Mithrim_Montes', "Titan's highest known peak", True),
    (11165, 'Mount Etna', 'Earth', 'Mount_Etna', 'blows volcanic smoke rings', False),
    (11249, 'Mount Hood', 'Earth', 'Mount_Hood', "Oregon's highest point", False),
    (11309, 'Emi Koussi', 'Earth', 'Emi_Koussi', "Chad's highest point", False),
    (11401, 'Volcán Barú', 'Earth', 'Volcán_Barú', 'Panama: see both oceans from the top', False),
    (11414, 'Mulhacén', 'Earth', 'Mulhacén', "mainland Spain's highest point", False),
    (11424, 'Thabana Ntlenyana', 'Earth', 'Thabana_Ntlenyana', 'highest point in southern Africa', False),
    (11847, 'Cheekha Dar', 'Earth', 'Cheekha_Dar', "Iraq's highest point", False),
    (12028, "Jabal An-Nabi Shu'ayb", 'Earth', "Jabal_an-Nabi_Shu'ayb", "Arabia's highest point", False),
    (12119, 'Gunnbjørn Fjeld', 'Earth', 'Gunnbjørn_Fjeld', "Greenland's highest point", False),
    (12218, 'Aoraki / Mount Cook', 'Earth', 'Aoraki_/_Mount_Cook', "New Zealand's highest point", False),
    (12389, 'Mount Fuji', 'Earth', 'Mount_Fuji', 'climb it once; only fools climb twice', True),
    (12461, 'Grossglockner', 'Earth', 'Grossglockner', "Austria's highest point", False),
    (12536, 'Cerro Chirripó', 'Earth', 'Cerro_Chirripó', "Costa Rica's highest point", False),
    (12637, 'Humphreys Peak', 'Earth', 'Humphreys_Peak', "Arizona's highest point", False),
    (12668, 'Borah Peak', 'Earth', 'Borah_Peak', "Idaho's highest point", False),
    (12807, 'Granite Peak', 'Earth', 'Granite_Peak_(Montana)', "Montana's highest point", False),
    (12967, 'Yushan', 'Earth', 'Yushan_(mountain)', "Taiwan's highest point", False),
    (13123, 'Ahuna Mons', 'Ceres', 'Ahuna_Mons', 'an ice volcano', True),
    (13147, 'Boundary Peak', 'Earth', 'Boundary_Peak_(Nevada)', "Nevada's highest point", False),
    (13167, 'Wheeler Peak', 'Earth', 'Wheeler_Peak_(New_Mexico)', "New Mexico's highest point", False),
    (13255, 'Mount Cameroon', 'Earth', 'Mount_Cameroon', "Cameroon's highest point", False),
    (13419, 'Mount Aragats', 'Earth', 'Mount_Aragats', "Armenia's highest point", False),
    (13435, 'Mount Kinabalu', 'Earth', 'Mount_Kinabalu', 'still grows ~5 mm a year', False),
    (13534, 'Kings Peak', 'Earth', 'Kings_Peak_(Utah)', "Utah's highest point", False),
    (13671, 'Jbel Toubkal', 'Earth', 'Toubkal', 'highest in the Atlas Mountains', False),
    (13789, 'Volcán Tajumulco', 'Earth', 'Volcán_Tajumulco', 'highest in Central America', False),
    (13803, 'Mauna Kea', 'Earth', 'Mauna_Kea', "Hawaii's highest point", True),
    (13809, 'Gannett Peak', 'Earth', 'Gannett_Peak', "Wyoming's highest point", False),
    (14107, 'Pikes Peak', 'Earth', 'Pikes_Peak', "inspired 'America the Beautiful'", True),
    (14291, 'Khüiten Peak', 'Earth', 'Khüiten_Peak', "Mongolia's highest point", False),
    (14406, 'Mount Rainier', 'Earth', 'Mount_Rainier', "Washington's highest point", True),
    (14440, 'Mount Elbert', 'Earth', 'Mount_Elbert', "Colorado's highest point", False),
    (14505, 'Mount Whitney', 'Earth', 'Mount_Whitney', 'highest in the contiguous US', True),
    (14652, 'Mount Bazardüzü', 'Earth', 'Mount_Bazardüzü', "Azerbaijan's highest point", False),
    (14692, 'Matterhorn', 'Earth', 'Matterhorn', 'carved by glaciers into a horn', True),
    (14764, 'Mons Hadley', 'Moon', 'Mons_Hadley', 'Apollo 15 landed at its foot', True),
    (14787, 'Mount Karisimbi', 'Earth', 'Mount_Karisimbi', "Rwanda's highest point", False),
    (14793, 'Mount Wilhelm', 'Earth', 'Mount_Wilhelm', "Papua New Guinea's highest point", False),
    (14928, 'Ras Dashen', 'Earth', 'Ras_Dashen', "Ethiopia's highest point", False),
    (15203, 'Dufourspitze', 'Earth', 'Dufourspitze', "Switzerland's highest point", False),
    (15420, 'Wright Mons', 'Pluto', 'Wright_Mons', 'a possible ice volcano', True),
    (15766, 'Mont Blanc', 'Earth', 'Mont_Blanc', 'highest in the Alps', True),
    (16024, 'Puncak Jaya', 'Earth', 'Puncak_Jaya', 'highest island peak on Earth', True),
    (16050, 'Vinson Massif', 'Earth', 'Vinson_Massif', "Antarctica's highest point", True),
    (16076, 'Maat Mons', 'Venus', 'Maat_Mons', "Venus' highest volcano", True),
    (16332, 'Pico Bolívar', 'Earth', 'Pico_Bolívar', "Venezuela's highest point", False),
    (16762, 'Mount Stanley', 'Earth', 'Mount_Stanley', "DR Congo and Uganda's highest point", False),
    (16854, 'Mount Ararat', 'Earth', 'Mount_Ararat', "where Noah's Ark is said to have landed", True),
    (17057, 'Mount Kenya', 'Earth', 'Mount_Kenya', 'winter every night, summer every day', True),
    (17070, 'Shkhara', 'Earth', 'Shkhara', "Georgia's (the country's) highest point", False),
    (17388, 'Mons Huygens', 'Moon', 'Mons_Huygens', "the Moon's tallest named mountain", True),
    (18045, 'Mount Sharp', 'Mars', 'Mount_Sharp', 'the Curiosity rover is climbing it', True),
    (18402, 'Mount Damavand', 'Earth', 'Mount_Damavand', 'highest volcano in Asia', False),
    (18491, 'Pico de Orizaba', 'Earth', 'Pico_de_Orizaba', "Mexico's highest point", False),
    (18510, 'Mount Elbrus', 'Earth', 'Mount_Elbrus', "Europe's highest point", True),
    (18947, 'Pico Cristóbal Colón', 'Earth', 'Pico_Cristóbal_Colón', 'Colombia, 26 miles from the sea', False),
    (19295, 'Hkakabo Razi', 'Earth', 'Hkakabo_Razi', "Myanmar's highest point", False),
    (19341, 'Kilimanjaro', 'Earth', 'Mount_Kilimanjaro', "Africa's highest point", True),
    (19551, 'Mount Logan', 'Earth', 'Mount_Logan', "Canada's highest point", False),
    (19685, 'Mons Mouton', 'Moon', 'Mons_Mouton', "near the Moon's south pole", True),
    (20300, 'Anseris Mons', 'Mars', 'Anseris_Mons', None, True),
    (20310, 'Denali', 'Earth', 'Denali', "North America's highest point", True),
    (20341, 'Tenzing Montes', 'Pluto', 'Tenzing_Montes', 'named after Tenzing Norgay', True),
    (20548, 'Chimborazo', 'Earth', 'Chimborazo', "farthest summit from Earth's center", False),
    (20997, 'Maxwell Montes', 'Venus', 'Maxwell_Montes', "Venus' highest mountains", True),
    (21463, 'Sajama', 'Earth', 'Nevado_Sajama', "Bolivia's highest point", False),
    (22205, 'Huascarán', 'Earth', 'Huascarán', "Peru's highest point", False),
    (22615, 'Ojos del Salado', 'Earth', 'Ojos_del_Salado', 'the highest volcano on Earth', False),
    (22858, 'Aconcagua', 'Earth', 'Aconcagua', 'highest outside Asia', True),
    (22966, "Herschel's central peak", 'Mimas', 'Herschel_(Mimantean_crater)', 'makes Mimas look like the Death Star', True),
    (22999, 'Khan Tengri', 'Earth', 'Khan_Tengri', "Kazakhstan's highest point", False),
    (24406, 'Jengish Chokusu', 'Earth', 'Jengish_Chokusu', "Tian Shan's highest point", False),
    (24580, 'Noshaq', 'Earth', 'Noshaq', "Afghanistan's highest point", False),
    (24590, 'Ismoil Somoni Peak', 'Earth', 'Ismoil_Somoni_Peak', 'formerly Communism Peak', False),
    (24840, 'Gangkhar Puensum', 'Earth', 'Gangkhar_Puensum', 'the highest unclimbed mountain', False),
    (25289, 'Tirich Mir', 'Earth', 'Tirich_Mir', 'highest in the Hindu Kush', False),
    (25551, 'Rakaposhi', 'Earth', 'Rakaposhi', None, False),
    (25646, 'Nanda Devi', 'Earth', 'Nanda_Devi', "India's highest wholly inside India", False),
    (26545, 'Annapurna', 'Earth', 'Annapurna', 'first 8,000 m peak climbed (1950)', True),
    (26660, 'Nanga Parbat', 'Earth', 'Nanga_Parbat', "'Killer Mountain'", False),
    (26781, 'Manaslu', 'Earth', 'Manaslu', None, False),
    (26795, 'Dhaulagiri', 'Earth', 'Dhaulagiri', None, False),
    (26864, 'Cho Oyu', 'Earth', 'Cho_Oyu', None, False),
    (27559, 'Pavonis Mons', 'Mars', 'Pavonis_Mons', 'a candidate space-elevator anchor', True),
    (27838, 'Makalu', 'Earth', 'Makalu', None, False),
    (27940, 'Lhotse', 'Earth', 'Lhotse', "Everest's next-door neighbour", False),
    (28169, 'Kangchenjunga', 'Earth', 'Kangchenjunga', 'first climbers stopped short of the top', True),
    (28251, 'K2', 'Earth', 'K2', 'the Savage Mountain', True),
    (29032, 'Mount Everest', 'Earth', 'Mount_Everest', "Earth's highest point", True),
    (33465, 'Mauna Kea, from the sea floor', 'Earth', 'Mauna_Kea', 'taller than Everest, base to peak', True),
    (34449, 'Euboea Montes', 'Io', 'Euboea_Montes', 'on the most volcanic world known', True),
    (38386, 'Arsia Mons', 'Mars', 'Arsia_Mons', None, True),
    (41339, 'Elysium Mons', 'Mars', 'Elysium_Mons', None, True),
    (49000, 'Ascraeus Mons', 'Mars', 'Ascraeus_Mons', None, True),
    (57415, 'Boösaule Montes', 'Io', 'Boösaule_Montes', "Io's highest mountain", True),
    (65617, 'Equatorial ridge of Iapetus', 'Iapetus', 'Equatorial_ridge_on_Iapetus', 'makes Iapetus look like a walnut', True),
    (71850, 'Olympus Mons', 'Mars', 'Olympus_Mons', 'the tallest volcano in the Solar System', True),
    (82021, "Máni's peak", '307261 Máni', '307261_Máni', 'found by a 2020 occultation, give or take 5 km', True),
]]
_HEIGHTS = [p.feet for p in PEAKS]
