/**
 * Surveys created on the admin page.
 *
 * A created survey is an ordinary survey config: the template in
 * templates/minimal.json (prompt, probe taxonomy, model, labels) plus the few
 * fields the form asks for (title, questions, follow-ups per question, closing
 * date, consent text). It goes through the same schema, gets the same
 * content-hash version, and is stored in survey.survey_configs like a file
 * would be; survey.surveys marks which version is current. Everything the
 * engine and the participant page do is identical for both kinds.
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fromRaw, type LoadedSurvey } from './load.js';

export const TEMPLATE_FILE = 'templates/minimal.json';

/** Shown before the first question unless the form supplies its own text. */
export const DEFAULT_CONSENT = `# Before you start

You are being asked to take part in a short adaptive survey: a typed conversation in which a fixed set of questions is followed by short follow-up questions generated by a language model running on Virginia Tech's own servers. The model never grades or evaluates what you write.

- Taking part is voluntary. You can skip any question with **Next question** and end at any time with **Stop**; whatever you have entered is kept.
- Your answers are stored under a code, not your name. The list linking codes to logins is kept separately by the research team and is destroyed when the study ends.
- Nothing you type is sent to any service outside Virginia Tech.

If you have questions, contact the research team that sent you this link.`;

export interface CreateSurveyInput {
  title: string;
  /** One question per entry; blank entries are dropped. */
  questions: string[];
  /** Follow-ups the model may ask per question (0 to 3). */
  maxProbes: number;
  /** YYYY-MM-DD; the survey closes at 23:59:59 America/New_York on that day. Default: 90 days out. */
  closesAt?: string | undefined;
  consentMarkdown?: string | undefined;
  agreeLabel?: string | undefined;
  opening?: string | undefined;
  closing?: string | undefined;
  systemPrompt?: string | undefined;
}

export interface CreateDefaults {
  consentMarkdown: string;
  agreeLabel: string;
  opening: string;
  closing: string;
  systemPrompt: string;
  maxProbes: number;
}

interface Template {
  consent: { agreeLabel: string; declineLabel: string };
  opening: string;
  closing: string;
  probing: Record<string, unknown> & { systemPrompt: string };
  model: Record<string, unknown>;
}

let cached: Template | null = null;

export function loadTemplate(file = TEMPLATE_FILE): Template {
  if (!cached) cached = JSON.parse(readFileSync(resolve(file), 'utf8')) as Template;
  return cached;
}

/** What the "New survey" form is prefilled with. */
export function createDefaults(): CreateDefaults {
  const t = loadTemplate();
  return {
    consentMarkdown: DEFAULT_CONSENT,
    agreeLabel: t.consent.agreeLabel,
    opening: t.opening,
    closing: t.closing,
    systemPrompt: t.probing.systemPrompt,
    maxProbes: 1,
  };
}

/** "CS 2114 reflections, Fall!" → "cs-2114-reflections-fall"; never empty; at most 40 chars. */
export function slugify(title: string): string {
  const s = title
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '') // strip the combining marks NFKD split off
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40)
    .replace(/-+$/g, '');
  return s || 'survey';
}

/** First of base, base-2, base-3, … that `taken` does not claim. */
export function uniqueId(base: string, taken: (id: string) => boolean): string {
  if (!taken(base)) return base;
  for (let n = 2; n < 1000; n++) {
    const id = `${base}-${n}`;
    if (!taken(id)) return id;
  }
  throw new Error('could not allocate a survey id');
}

/** Where the participants are; a closing date on the form means the end of that day here, not on the VM's clock. */
export const SURVEY_TIME_ZONE = 'America/New_York';

function tzOffsetMinutes(at: Date, timeZone: string): number {
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone,
    hourCycle: 'h23',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  }).formatToParts(at);
  const get = (type: string) => Number(parts.find((p) => p.type === type)?.value ?? 0);
  const wallClockAsUtc = Date.UTC(get('year'), get('month') - 1, get('day'), get('hour'), get('minute'), get('second'));
  return Math.round((wallClockAsUtc - at.getTime()) / 60_000);
}

/** The instant at which `YYYY-MM-DD` ends (23:59:59) in `timeZone`. Throws on a malformed date. */
export function endOfDayIn(date: string, timeZone = SURVEY_TIME_ZONE): Date {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new Error('Closing date must be YYYY-MM-DD');
  const naive = Date.parse(`${date}T23:59:59Z`);
  if (Number.isNaN(naive)) throw new Error('Closing date must be YYYY-MM-DD');
  return new Date(naive - tzOffsetMinutes(new Date(naive), timeZone) * 60_000);
}

const pick = (given: string | undefined, fallback: string): string => {
  const s = given?.trim();
  return s ? s : fallback;
};

/**
 * Assemble the raw config and validate it. Throws the schema's readable
 * message on a bad input (empty questions, bad date, …).
 */
export function buildCreatedSurvey(input: CreateSurveyInput, opts: { id: string; creatorPid: string; now?: Date }): LoadedSurvey {
  const t = loadTemplate();
  const now = opts.now ?? new Date();
  const questions = input.questions.map((q) => q.trim()).filter(Boolean);
  if (!questions.length) throw new Error('At least one question is required');
  if (!Number.isInteger(input.maxProbes) || input.maxProbes < 0 || input.maxProbes > 3) throw new Error('Follow-ups per question must be 0 to 3');

  let closes: Date;
  if (input.closesAt) {
    closes = endOfDayIn(input.closesAt);
    if (closes.getTime() <= now.getTime()) throw new Error('Closing date must be in the future');
  } else {
    closes = new Date(now.getTime() + 90 * 86_400_000);
  }

  const raw = {
    id: opts.id,
    title: input.title.trim(),
    notes: `Created on the admin page on ${now.toISOString().slice(0, 10)}.`,
    status: 'open',
    roles: { researchers: [opts.creatorPid], keyholders: [opts.creatorPid] },
    eligibility: { requireAdult: true, roster: 'none', guestAccess: false },
    consent: {
      sheetMarkdown: pick(input.consentMarkdown, DEFAULT_CONSENT),
      agreeLabel: pick(input.agreeLabel, t.consent.agreeLabel),
      declineLabel: t.consent.declineLabel,
    },
    opening: pick(input.opening, t.opening),
    closing: pick(input.closing, t.closing),
    waves: [
      {
        id: 'main',
        label: 'Survey',
        opensAt: now.toISOString(),
        closesAt: closes.toISOString(),
        starters: questions.map((text, i) => ({ id: `q${i + 1}`, text })),
      },
    ],
    probing: {
      ...t.probing,
      maxProbesPerStarter: input.maxProbes,
      maxTurnsPerSession: questions.length * (1 + input.maxProbes),
      systemPrompt: pick(input.systemPrompt, t.probing.systemPrompt),
    },
    model: t.model,
  };
  return fromRaw(raw, `admin-created survey "${opts.id}"`, 'db');
}

/** A copy of a loaded survey with one top-level field changed, re-validated and re-hashed. */
export function withStatus(loaded: LoadedSurvey, status: 'open' | 'closed'): LoadedSurvey {
  const raw = { ...(loaded.raw as Record<string, unknown>), status };
  return fromRaw(raw, `status change for "${loaded.config.id}"`, loaded.source);
}
